// Generated by scripts/sync-profile-portrait.mjs.
// Keep exactly one JPG, JPEG, or PNG source image in public/profile.

export const profilePortrait = {
  src: '/profile/generated/portrait-9175d26f12ad.png',
} as const
