// Generated by scripts/sync-profile-portrait.mjs.
// Keep exactly one JPG, JPEG, or PNG source image in public/profile.

export const profilePortrait = {
  src: '/profile/generated/portrait-381c3fbd8bf2.jpg',
} as const
